name = "stageroom-workers"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
LIVEKIT_URL = "wss://yonumbr-live-streamers-gr2u0h9p.livekit.cloud"
LIVEKIT_API_KEY = "APIBeG2hXfByiSx"
LIVEKIT_API_SECRET = "7daeNUNlqYuyx1aV7onunIFX50CY7jvPWUFVfAaHOo7"
JWT_SECRET = "stageroom-jwt-secret-change-in-production-2026"
PAYSTACK_SECRET_KEY = "sk_test_e17b66c0d1b9e62aad250c745c822ef742f73e7f"
PAYSTACK_PUBLIC_KEY = "pk_test_8d63fe7107bbd9707882afb2f8aa0a446a0d86fb"
R2_BUCKET_NAME = "streamers"
R2_PUBLIC_URL = "https://playstageroom.yonumbr.com"

[[d1_databases]]
binding = "DB"
database_name = "stageroomdb"
database_id = "5529733f-daaa-4711-a445-8f6897934ad9"

[[r2_buckets]]
binding = "R2"
bucket_name = "streamers"

[env.production]
LIVEKIT_URL = "wss://yonumbr-live-streamers-gr2u0h9p.livekit.cloud"

[env.staging]
